/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pendataanmahasiswa;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author meone
 */
public class AdminForm extends javax.swing.JFrame {

    /**
     * Creates new form AdminForm
     */
    
    Mahasiswa mhs = new Mahasiswa();
    public AdminForm() {
        initComponents();
        
//        mhs.FillToTable(TableData, "");
    }
    
    boolean validateText(){
        if (nameAdmin.getText().equals("") || ttlAdmin.getDate() == null || npmAdmin.getText().equals("") || prodiAdmin.getText().equals(" ")
                || nomorAdmin.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Mohon Lengkapi Data Anda!!");
            return false;
        }else if ( ttlAdmin.getDate().compareTo(new Date()) > 0){
            JOptionPane.showMessageDialog(null, "Tolong isi Tanggal lahir dengan Benar");
            return false;
        }else{
            return true;
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        SearchNama = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        BackToLoginButton = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableData = new javax.swing.JTable();
        prodiAdmin = new javax.swing.JTextField();
        nomorAdmin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        priaButtonAdmin = new javax.swing.JRadioButton();
        wanitaButtonAdmin = new javax.swing.JRadioButton();
        ttlAdmin = new com.toedter.calendar.JDateChooser();
        npmAdmin = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        RefreshButton = new javax.swing.JButton();
        nameAdmin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 204, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bitstream Charter", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tampilan Data Mahasiswa");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 100));

        SearchNama.setBackground(new java.awt.Color(153, 153, 153));
        SearchNama.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        SearchNama.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SearchNama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.add(SearchNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 500, 320, 35));

        SearchButton.setBackground(new java.awt.Color(153, 153, 153));
        SearchButton.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        SearchButton.setText("Search");
        SearchButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });
        jPanel2.add(SearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 540, 100, 35));

        BackToLoginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pendataanmahasiswa/Back.png"))); // NOI18N
        BackToLoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackToLoginButtonMouseClicked(evt);
            }
        });
        jPanel2.add(BackToLoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pendataanmahasiswa/ProfileAdmin.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

        jLabel11.setFont(new java.awt.Font("Bitstream Charter", 1, 36)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("UNIVERSITAS Y");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 700, 100));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 650));

        jLabel3.setFont(new java.awt.Font("Bitstream Charter", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("WELCOME TO UNIVERSITY Y");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 700, 50));

        jLabel4.setFont(new java.awt.Font("Bitstream Charter", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Manage Your Student");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, 700, 50));

        TableData.setBackground(new java.awt.Color(0, 204, 0));
        TableData.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        TableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Siswa", "Prodi", "Jenis Kelamin", "Tanggal Lahir", "No Telepon", "NPM"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableData);
        if (TableData.getColumnModel().getColumnCount() > 0) {
            TableData.getColumnModel().getColumn(0).setResizable(false);
            TableData.getColumnModel().getColumn(1).setResizable(false);
            TableData.getColumnModel().getColumn(2).setResizable(false);
            TableData.getColumnModel().getColumn(3).setResizable(false);
            TableData.getColumnModel().getColumn(4).setResizable(false);
            TableData.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, 700, 220));

        prodiAdmin.setBackground(new java.awt.Color(0, 204, 0));
        prodiAdmin.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        prodiAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(prodiAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 380, 350, -1));

        nomorAdmin.setBackground(new java.awt.Color(0, 204, 0));
        nomorAdmin.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        nomorAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nomorAdmin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nomorAdminKeyTyped(evt);
            }
        });
        jPanel1.add(nomorAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 500, 350, -1));

        jLabel5.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        jLabel5.setText("Nama :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 340, -1, -1));

        jLabel6.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        jLabel6.setText("Prodi :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 380, -1, -1));

        jLabel7.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        jLabel7.setText("Jenis Kelamin :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 420, -1, -1));

        jLabel8.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        jLabel8.setText("Nomor Telepon :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 500, -1, -1));

        jLabel9.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        jLabel9.setText("NPM :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 540, -1, -1));

        jLabel10.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        jLabel10.setText("Tanggal lahir :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 460, -1, -1));

        buttonGroup1.add(priaButtonAdmin);
        priaButtonAdmin.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        priaButtonAdmin.setText("PRIA");
        jPanel1.add(priaButtonAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 420, 175, -1));

        buttonGroup1.add(wanitaButtonAdmin);
        wanitaButtonAdmin.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        wanitaButtonAdmin.setText("WANITA");
        jPanel1.add(wanitaButtonAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 420, 175, -1));

        ttlAdmin.setBackground(new java.awt.Color(153, 153, 153));
        ttlAdmin.setDateFormatString("d - MM - y");
        ttlAdmin.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        jPanel1.add(ttlAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 460, 350, -1));

        npmAdmin.setBackground(new java.awt.Color(0, 204, 0));
        npmAdmin.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        npmAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(npmAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 540, 350, -1));

        AddButton.setBackground(new java.awt.Color(0, 204, 0));
        AddButton.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        AddButton.setText("ADD");
        AddButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 590, 100, -1));

        EditButton.setBackground(new java.awt.Color(0, 204, 0));
        EditButton.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        EditButton.setText("EDIT");
        EditButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });
        jPanel1.add(EditButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 590, 100, -1));

        DeleteButton.setBackground(new java.awt.Color(0, 204, 0));
        DeleteButton.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        DeleteButton.setText("DELETE");
        DeleteButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(DeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 590, 100, -1));

        RefreshButton.setBackground(new java.awt.Color(0, 204, 0));
        RefreshButton.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        RefreshButton.setText("REFRESH");
        RefreshButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        RefreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshButtonActionPerformed(evt);
            }
        });
        jPanel1.add(RefreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 590, 100, -1));

        nameAdmin.setBackground(new java.awt.Color(0, 204, 0));
        nameAdmin.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        nameAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(nameAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 340, 350, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
        String cari = SearchNama.getText().trim();
        TableData.setModel(new DefaultTableModel(null, new Object[]{"Nama Siswa","Prodi", "Jenis Kelamin", "Tanggal Lahir", "No Telepon", "NPM"}));
        mhs.Seacrh(TableData, cari);
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void BackToLoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackToLoginButtonMouseClicked
        // TODO add your handling code here:
        new LoginForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackToLoginButtonMouseClicked

    private void TableDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableDataMouseClicked
        // TODO add your handling code here:
        
        int index = TableData.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) TableData.getModel();
        
        nameAdmin.setText(model.getValueAt(index, 0).toString());
        prodiAdmin.setText(model.getValueAt(index, 1).toString());
        nomorAdmin.setText(model.getValueAt(index, 4).toString());
        npmAdmin.setText(model.getValueAt(index, 5).toString());
        if (model.getValueAt(index, 2).toString().equals("PRIA")){
            priaButtonAdmin.setSelected(true);
            priaButtonAdmin.setSelected(false);
        }else{
            wanitaButtonAdmin.setSelected(true);
            wanitaButtonAdmin.setSelected(false);
        }
        
        Date ttl;
        
        try {
            ttl = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(index, 3).toString());
            ttlAdmin.setDate(ttl);
        } catch (ParseException ex) {
            Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_TableDataMouseClicked

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        String nama = nameAdmin.getText().trim();
        String prodi = prodiAdmin.getText();
        String gender;
        if (priaButtonAdmin.isSelected()){
            gender = "PRIA";
        }else{
            gender = "WANITA";
        }
        String nomor = nomorAdmin.getText().trim();
        String npm = npmAdmin.getText().trim();
        
        if (validateText()){
            SimpleDateFormat dt = new SimpleDateFormat("yyyy-MM-dd");
            String date = dt.format(ttlAdmin.getDate());
            
            Mahasiswa mhs = new Mahasiswa();
            
            mhs.InsertUpdateDelete('i', nama, prodi, null, null, gender, date, npm, nomor, nama);
        }
    }//GEN-LAST:event_AddButtonActionPerformed

    private void RefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshButtonActionPerformed
        // TODO add your handling code here:
        TableData.setModel(new DefaultTableModel(null, new Object[]{"Nama Siswa","Prodi", "Jenis Kelamin", "Tanggal Lahir", "No Telepon", "NPM"}));
        mhs.FillToTable(TableData, "");
    }//GEN-LAST:event_RefreshButtonActionPerformed

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        // TODO add your handling code here:
        int index = TableData.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) TableData.getModel();
        String Nama_ubah = model.getValueAt(index, 0).toString();
        String nama = nameAdmin.getText().trim();
        String prodi = prodiAdmin.getText();
        String gender;
        if (priaButtonAdmin.isSelected()){
            gender = "PRIA";
        }else{
            gender = "WANITA";
        }
        String nomor = nomorAdmin.getText().trim();
        String npm = npmAdmin.getText().trim();
        
        if (validateText()){
            SimpleDateFormat dt = new SimpleDateFormat("yyyy-MM-dd");
            String date = dt.format(ttlAdmin.getDate());
            
            Mahasiswa mhs = new Mahasiswa();
            
            mhs.InsertUpdateDelete('u', nama, prodi, null, null, gender, date, npm, nomor, Nama_ubah);
        }
    }//GEN-LAST:event_EditButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
        String nama = nameAdmin.getText().trim();
        if (nameAdmin.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Pastikan data yang akan dihapus!");
        }else{
            Mahasiswa mhs = new Mahasiswa();
            
            mhs.InsertUpdateDelete('d', nama, null, null, null, null, null, null, null, null);
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        new LoginForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void nomorAdminKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomorAdminKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_nomorAdminKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JLabel BackToLoginButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton EditButton;
    private javax.swing.JButton RefreshButton;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField SearchNama;
    private javax.swing.JTable TableData;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameAdmin;
    private javax.swing.JTextField nomorAdmin;
    private javax.swing.JTextField npmAdmin;
    private javax.swing.JRadioButton priaButtonAdmin;
    private javax.swing.JTextField prodiAdmin;
    private com.toedter.calendar.JDateChooser ttlAdmin;
    private javax.swing.JRadioButton wanitaButtonAdmin;
    // End of variables declaration//GEN-END:variables
}
