/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pendataanmahasiswa;
import com.mysql.jdbc.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author meone
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lUsername = new javax.swing.JTextField();
        lPassword = new javax.swing.JPasswordField();
        lProfile = new javax.swing.JComboBox<>();
        loginButton = new javax.swing.JButton();
        goToRegisMenu = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 204, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lUsername.setFont(new java.awt.Font("C059", 0, 18)); // NOI18N
        lUsername.setForeground(new java.awt.Color(153, 153, 153));
        lUsername.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        lUsername.setText("Username");
        lUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lUsernameMouseClicked(evt);
            }
        });
        jPanel1.add(lUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, 570, -1));

        lPassword.setFont(new java.awt.Font("C059", 0, 18)); // NOI18N
        lPassword.setForeground(new java.awt.Color(153, 153, 153));
        lPassword.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        lPassword.setText("Password");
        lPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lPasswordMouseClicked(evt);
            }
        });
        jPanel1.add(lPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 280, 570, -1));

        lProfile.setFont(new java.awt.Font("C059", 0, 18)); // NOI18N
        lProfile.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Masuk Sebagai", "Siswa", "Admin" }));
        jPanel1.add(lProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 330, 570, -1));

        loginButton.setBackground(new java.awt.Color(102, 102, 102));
        loginButton.setFont(new java.awt.Font("Bitstream Charter", 1, 24)); // NOI18N
        loginButton.setText("SIGN IN!");
        loginButton.setToolTipText("");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jPanel1.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 545, 570, 50));

        goToRegisMenu.setFont(new java.awt.Font("C059", 0, 15)); // NOI18N
        goToRegisMenu.setText("Belum Memiliki Akun? SIlahkan Daftar Di Sini!");
        goToRegisMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goToRegisMenuMouseClicked(evt);
            }
        });
        jPanel1.add(goToRegisMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 610, -1, -1));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Bitstream Charter", 1, 48)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Universitas Y");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 700, 100));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pendataanmahasiswa/ProfileUniv.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pendataanmahasiswa/Exit.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 650));

        jLabel1.setFont(new java.awt.Font("C059", 0, 42)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SIGN IN WITH YOUR ACCOUNT!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 700, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void goToRegisMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goToRegisMenuMouseClicked
        // TODO add your handling code here:
        new RegisForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_goToRegisMenuMouseClicked

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        PreparedStatement st;
        ResultSet rs;
        if (lUsername.getText().equalsIgnoreCase("Username") || lPassword.getText().equalsIgnoreCase("Password")){
            JOptionPane.showMessageDialog(null, "Mohon Masukan username atau Password Anda!");
        }else{
            String username = lUsername.getText().trim();
            String password = lPassword.getText().trim();
            String profile = lProfile.getItemAt(lProfile.getSelectedIndex());
            String query = "SELECT `user`, `profile`, `pass` FROM `Login` WHERE user = ? AND profile = ? AND pass = ?";

            try {
                st = (PreparedStatement) MyConncetion.getConnection().prepareStatement(query);

                st.setString(1, username);
                st.setString(2, profile);
                st.setString(3, password);

                rs = st.executeQuery();

                if( rs.next() ){
                    JOptionPane.showMessageDialog(null, "Anda Login Sebagai " + profile);
                    if (profile.equals("Siswa")){
                        new UserForm().setVisible(true);
                        this.dispose();
                    }else{
                        new AdminForm().setVisible(true);
                        this.dispose();
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Username or Password Anda tidak Ditemukan!");
                    lUsername.setText("Username");
                    lPassword.setText("Password");
                }
            } catch (SQLException ex) {
                Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_loginButtonActionPerformed

    private void lUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lUsernameMouseClicked
        // TODO add your handling code here:
        lUsername.setText("");
    }//GEN-LAST:event_lUsernameMouseClicked

    private void lPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lPasswordMouseClicked
        // TODO add your handling code here:
        lPassword.setText("");
    }//GEN-LAST:event_lPasswordMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel goToRegisMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField lPassword;
    private javax.swing.JComboBox<String> lProfile;
    private javax.swing.JTextField lUsername;
    private javax.swing.JButton loginButton;
    // End of variables declaration//GEN-END:variables
}
