/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pendataanmahasiswa;

import com.mysql.jdbc.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author meone
 */
public class RegisForm extends javax.swing.JFrame {
    String[] arrProfile;
    

    /**
     * Creates new form RegisForm
     */
    public RegisForm() {
        initComponents();
    }
    
    boolean cekUsername(String User){
        boolean cek = false;
        
        PreparedStatement st;
        ResultSet rs;
        
        String query = "SELECT `user` FROM `Login` WHERE user = ?";
        
        try {
            
            st = (PreparedStatement) MyConncetion.getConnection().prepareStatement(query);               
            st.setString(1, User);
        
            rs = st.executeQuery();
            
            if (rs.next()){
                cek = true;
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(RegisForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        return cek;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rUsername = new javax.swing.JTextField();
        rPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        rProfile = new javax.swing.JComboBox<>();
        regisButton = new javax.swing.JButton();
        backToLoginMenu = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 204, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("C059", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Universitas Y");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 700, 100));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pendataanmahasiswa/ProfileUniv.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pendataanmahasiswa/Back.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 650));

        rUsername.setFont(new java.awt.Font("C059", 0, 18)); // NOI18N
        rUsername.setForeground(new java.awt.Color(153, 153, 153));
        rUsername.setText("Username");
        rUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rUsernameMouseClicked(evt);
            }
        });
        jPanel1.add(rUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, 570, -1));

        rPassword.setFont(new java.awt.Font("C059", 0, 18)); // NOI18N
        rPassword.setForeground(new java.awt.Color(153, 153, 153));
        rPassword.setText("Password");
        rPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rPasswordMouseClicked(evt);
            }
        });
        jPanel1.add(rPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 280, 570, -1));

        jLabel2.setFont(new java.awt.Font("C059", 0, 18)); // NOI18N
        jLabel2.setText("Pilih Jenis User");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 330, -1, -1));

        rProfile.setFont(new java.awt.Font("C059", 0, 18)); // NOI18N
        rProfile.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Siswa" }));
        jPanel1.add(rProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 330, 160, -1));

        regisButton.setBackground(new java.awt.Color(102, 102, 102));
        regisButton.setFont(new java.awt.Font("Bitstream Charter", 1, 24)); // NOI18N
        regisButton.setText("REGISTER NOW");
        regisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regisButtonActionPerformed(evt);
            }
        });
        jPanel1.add(regisButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 545, 570, 50));

        backToLoginMenu.setFont(new java.awt.Font("C059", 0, 15)); // NOI18N
        backToLoginMenu.setText("Sudah Memiliki akun? Klik di sini Untuk Sign In!");
        backToLoginMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backToLoginMenuMouseClicked(evt);
            }
        });
        jPanel1.add(backToLoginMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 610, -1, -1));

        jLabel3.setFont(new java.awt.Font("C059", 0, 42)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CREATE YOUR ACCOUNT!");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 700, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backToLoginMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToLoginMenuMouseClicked
        // TODO add your handling code here:
        LoginForm login = new LoginForm();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backToLoginMenuMouseClicked

    private void regisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regisButtonActionPerformed
        // TODO add your handling code here:
        if (rUsername.getText().equalsIgnoreCase("Username") || rPassword.getText().equalsIgnoreCase("Password")){
            JOptionPane.showMessageDialog(null, "Mohon Masukan username atau Password Anda!");
        }else{
            String name = rUsername.getText().trim();
            String pass = rPassword.getText().trim();
            String profile = rProfile.getItemAt(rProfile.getSelectedIndex());
            boolean cek = cekUsername(name);
            
            PreparedStatement ps;
            String query = "INSERT INTO `Login`(`user`, `profile`, `pass`) VALUES (?,?,?)";
            
            try {
                
                if (cek){
                    JOptionPane.showMessageDialog(null, "Username Telah Digunakan!!");
                    rUsername.setText("");
                    rPassword.setText("");
                }else{
                    ps = (PreparedStatement) MyConncetion.getConnection().prepareStatement(query);
                
                    ps.setString(1, name);
                    ps.setString(2, profile);
                    ps.setString(3, pass);

                    if ( ps.executeUpdate() > 0 ){
                        JOptionPane.showMessageDialog(null, "User Telah Ditambahkan");
                        
                        //open form login
                        new LoginForm().setVisible(true);
                        this.dispose();
                    }
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(RegisForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_regisButtonActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        new LoginForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void rUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rUsernameMouseClicked
        // TODO add your handling code here:
        rUsername.setText("");
    }//GEN-LAST:event_rUsernameMouseClicked

    private void rPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rPasswordMouseClicked
        // TODO add your handling code here:
        rPassword.setText("");
    }//GEN-LAST:event_rPasswordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backToLoginMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField rPassword;
    private javax.swing.JComboBox<String> rProfile;
    private javax.swing.JTextField rUsername;
    private javax.swing.JButton regisButton;
    // End of variables declaration//GEN-END:variables
}
